install helm with custom ansible module working

diff --git a/provisioning/localtemplates/validate-context b/provisioning/localtemplates/validate-context
--- a/provisioning/localtemplates/validate-context
+++ b/provisioning/localtemplates/validate-context
@@ -8,7 +8,7 @@ set +e
 
 test=$(kubectl get nodes)
 if [ $? -ne 0 ]; then
-    echo "kubectl"
+    echo "kubectl failed with RC $?"
     exit 1
 fi
 
